name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '8.1' ]

    steps:
      - uses: actions/checkout@v2
      - run: composer validate
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: composer check
